Add in parameters for Named Values
hmcts/cnp-api-mgmt-arm-template pull request #6
Opened 2019-07-02 11:02 UTC by harmrai

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CNP-1344

### Change description ###

Add in Named Values for supporting parameterisation of policies.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2019-07-02 11:58 UTC, almmechanics requested changes
1. Replace the `apiManagementServiceName`variable with the parameter which has the name for it
1. Let the deployment resource group (i.e.  "[resourceGroup().location]") be used instead of `apiManagementResourceGroup`
1. It may be worth adding in additional metadata/description elements for the ARM parameters to make it easier for handover
1. remove the `secret:false` as the default is false if not provided (https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2019-01-01/service/properties)

2019-07-02 11:58 UTC, almmechanics commented on template/ccdDataStoreAPI.json
> +      "namedValueTag": {
`namedValueTag` never used

2019-07-02 14:31 UTC, almmechanics commented
"contentValue": "[parameters('apiContentValue')]",
            "contentFormat": "swagger-link-json"

should be
"value" and "format"

2019-07-02 14:36 UTC, almmechanics commented
Also `authenticationSettings`  and `subscriptionKeyParameterNames` are null by default so they can be lost

2019-07-03 10:16 UTC, harmrai commented
> ```
>         "contentValue": "[parameters('apiContentValue')]",
>         "contentFormat": "swagger-link-json"
> ```
> 
> should be
> "value" and "format"

Ahh, look likes these were renamed as part of the newer 2019-01-01 API. 2018-01-01 these were referred to as contentValue and contentFormat.

2019-07-04 12:32 UTC, almmechanics reviewed
Changes to VNet config accepted
Definition of named variables accepted

2019-07-04 12:37 UTC, almmechanics reviewed
changes accepted

2019-07-04 12:37 UTC, almmechanics approved these changes

2019-07-04 12:38 UTC, merged